### PR TITLE
Ooftonium changes

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Not sure how you'd like to handle the OSU stuff. Should I uncomment, should it be deleted, should it be in different files, or should it be in its own repo? 

What works best for you?

**Comment by ikz87** [comment]
All my personal stuff can be deleted from the main branch, that includes the osu things and anything related to non-everyday use apps

**Comment by ikz87** [comment]
Will merge and delete commented lines myself. Thank you for generalizing all username dependant paths

**Comment by ghost** [comment]
I think my path changes in the `rofi` dir broke things. How is it looking on your end?

**Comment by ikz87** [comment]
Same now that i checked but got it working by using ~ instead of ${HOME}, will fix that rn

**Comment by ikz87** [comment]
Now, the linking script seems like a good idea, but the colors.sh part of it should not go there. Now I realized I did a poor job of explaining how the wpgtk stuff worked. Will delete the file at `~/colors.sh` and put all colorscheme related stuff in `~/cache/wal` (since that's where it should go) and will add a readme explaining some things

**Pull request merged**
